### ISSUE TITLE
does can-isotp require the kernel mod or it's optional?

### ISSUE THREAD

**Issue by andrewarrow** [pylessard/python-can-isotp#11]
If I don't have the kernel mod:

https://github.com/hartkopp/can-isotp/blob/master/net/can/isotp.c

Installed, will python-can-isotp do that logic in the above c file all in python?

Or is that kernel mod a hard requirement for this package?

Thanks!

**Comment by pylessard** [comment]
Yes, it's optional. There is actually 2 parts to the package. An implementation of the protocol in python and a wrapper for the kernel module. 

You only need the kernel module if you try to import isotp.socket

isotp.TransportLayer won't try to load it.

Cheers

**Comment by andrewarrow** [comment]
ah, thank you, makes sense.
