### ISSUE TITLE
CanStack automatically stopped and program crashed

### ISSUE THREAD

**Issue by funnyrabbitvu** [pylessard/python-can-isotp#120]
Hi @pylessard,

Currently i met this issue, my program is crashed after successfully running an UDS sequence. Below is debug info that related to CanStack stopped and connection closed. Did this cause my program crashed? please help me to check this issue. 

Thank you and best regards,
Vu

[Debug info]
DEBUG:isotp:Stopping CanStack
DEBUG:isotp:Main thread is exiting
DEBUG:isotp:CanStack Stopped
INFO:Connection:Connection closed

**Comment by funnyrabbitvu** [comment]
Not an issue. I will close this, sorry for my misunderstanding.

**Comment by pylessard** [comment]
Good.
Consider using the ListenerBasedCanStack.  Just less troubles.
