### ISSUE TITLE
Single Frame larger than 8 bytes is not supported

### ISSUE THREAD

**Issue by lhrbu** [pylessard/python-can-isotp#131]
I trying to send a payload 0x10 0x01 to an ECU under CANFD ISO 15765-2 2016 and TX_DL as 64, we'd expect the can frame should be 0x00 0x02 0x10 x01 ..., but the library will still package the payload as 0x02 0x10 0x01 ...

![Capture](https://github.com/user-attachments/assets/ff30c319-4859-4cc2-94fd-000bccd2851b)

**Comment by hartkopp** [comment]
No, you are wrong. Please read ISO 15765-2 2016 carefully.

The escape sequence with 0x00 in the first byte only starts with PDU lengths greater than 7:

```
$ isotpsend -s 123 -d 321 -L 72:64:1 -D 2 vcan0
$ isotpsend -s 123 -d 321 -L 72:64:1 -D 8 vcan0
$ isotpsend -s 123 -d 321 -L 72:64:1 -D 7 vcan0
```


```
$ candump any
  vcan0  123  [03]  02 01 02
  vcan0  123  [12]  00 08 01 02 03 04 05 06 07 08 CC CC
  vcan0  123  [08]  07 01 02 03 04 05 06 07
```

**Comment by raccoon-forvia** [comment]
> No, you are wrong. Please read ISO 15765-2 2016 carefully.
> 
> The escape sequence with 0x00 in the first byte only starts with PDU lengths greater than 7:
> 
> ```
> $ isotpsend -s 123 -d 321 -L 72:64:1 -D 2 vcan0
> $ isotpsend -s 123 -d 321 -L 72:64:1 -D 8 vcan0
> $ isotpsend -s 123 -d 321 -L 72:64:1 -D 7 vcan0
> ```
> 
> ```
> $ candump any
>   vcan0  123  [03]  02 01 02
>   vcan0  123  [12]  00 08 01 02 03 04 05 06 07 08 CC CC
>   vcan0  123  [08]  07 01 02 03 04 05 06 07
> ```

Got your point, yes I missed the requirement that PDU length should greater than 7. Thanks a lot for your answer
