### ISSUE TITLE
One second delay occurs between consecutive frames.

### ISSUE THREAD

**Issue by HyoungSikKWON** [pylessard/python-can-isotp#134]
First of all, thank you very much for creating such a useful module.

When using CAN-FD, a delay of 1 second occurs between consecutive frames as shown below.
(candump log)

![image](https://github.com/user-attachments/assets/43830869-ef1c-43f1-b2a1-e2d68fe9e50e)

isotp_params setting values

isotp_params = {
    'stmin': 1,                            
    'blocksize': 8,                       
    'wftmax': 0,                         
    'tx_data_length': 8,                
    'tx_data_min_length': 8,
    'tx_padding': 0x55,                       
    'rx_flowcontrol_timeout': 2000,         
    'rx_consecutive_frame_timeout': 2000,  
    'max_frame_size': 4095,                 
    'can_fd': True,                        
    'bitrate_switch': True,                
    'rate_limit_enable': False,             
    'rate_limit_max_bitrate': 1000000,      
    'rate_limit_window_size': 0.2,          
    'listen_mode': False,       
    'override_receiver_stmin': 1,
   }

**Comment by pylessard** [comment]
You set ``override_receiver_stmin=1``   You are enforcing a delay of 1 second.
https://can-isotp.readthedocs.io/en/latest/isotp/implementation.html#override_receiver_stmin

I realize that there is a discrepency between ``stmin`` and ``override_received_stmin``. On takes byte value that maps to a time, the second takes a time value given as float.

**Comment by HyoungSikKWON** [comment]
Sorry for wasting your precious time. I understood it to be the same as the "stmin" parameter, not seconds. thank you. 
I will read the document carefully from now on.

**Comment by pylessard** [comment]
No worries. I would have assumed the same.
Passing a time values gives more freedom and does not constrain someone to use values available in iso15765
