### ISSUE TITLE
Consecutive Messages occasionally too fast

### ISSUE THREAD

**Issue by ghost** [pylessard/python-can-isotp#32]
Hi,

I'm using udsoncan to transfer a file over can-isotp. System is Windows.
During the transfer I occasionally get two consecutive messages, which have a very short sepeartion time, leading to my receiver dropping one of them. The receiver requests a separation time of 1 ms, while the messages are sent apart 300 microseconds. The following trace shows the sender (CAN-ID 0x10A) transfering a file using udsoncan to the receiver (CAN-ID 0x10B).
![grafik](https://user-images.githubusercontent.com/70009794/90869726-e97c6800-e398-11ea-84da-43dff669dd05.png)

Increasing the separation time up to 5 ms decreases the occurence of the two messages sent shortly after, but it still occures from time to time. In the following trace the seperation time is set to 5 ms and again sender (CAN-ID 0x10A) sends via udsoncan to the receiver (CAN-ID 0x10B).
![grafik](https://user-images.githubusercontent.com/70009794/90871575-93f58a80-e39b-11ea-9ed9-12b8c967c94d.png)

I use these isotp parameters:
```
isotp_params = {
        'stmin': 32,
        # Will request the sender to wait 32ms between consecutive frame. 0-127ms or 100-900ns with values from 0xF1-0xF9
        'blocksize': 8,  # Request the sender to send 8 consecutives frames before sending a new flow control message
        'wftmax': 0,  # Number of wait frame allowed before triggering an error
        'll_data_length': 8,  # Link layer (CAN layer) works with 8 byte payload (CAN 2.0)
        'tx_padding': 0xFF,  # Will pad all transmitted CAN messages with byte 0x00. None means no padding
        'rx_flowcontrol_timeout': 1000,
        # Triggers a timeout if a flow control is awaited for more than 1000 milliseconds
        'rx_consecutive_frame_timeout': 1000,
        # Triggers a timeout if a consecutive frame is awaited for more than 1000 milliseconds
        'squash_stmin_requirement': False
        # When sending, respect the stmin requirement of the receiver. If set to True, go as fast as possible.
    }
```
From my understanding this should be prevented by ST in isotp. Is there anything I am missing?

**Comment by pylessard** [comment]
Hi @VNiemann,
I am not sure what would be the solution here as I do not know the PCAN API. To understand the difference, you would need to dig into python-can module. 

I will check on my side when I will have time. Let me know if you have new informations.

You can also share a piece of C++ that shows how your bus is configured and how you send a message.

**Comment by pylessard** [comment]
Hi @VNiemann, Do you have an update on this?

**Comment by zorce** [comment]
Hi,
I can see the same issue on my windows Kvaser interface, but my receiver (embedded, ansi c) doesn't seem to have a problem with those fast sends. Thought I had the same issue but for me it was buffer sizes on the receiving end that made the reception to fail.
