### ISSUE TITLE
stack.process() got stuck during milti frame Tx

### ISSUE THREAD

**Issue by sylar89ash** [pylessard/python-can-isotp#43]
Hi,

Observed some weird behavior in my Python code for transmitting Multi-frame CAN MESSAGE.

code: 
While stack.transmitting():
    Stack.process()
    time.sleep(stack.sleep_time())

the execution hangs in stack.process() function call and eventually the while loop doesn’t break causing the whole code stuck.

please advise.

**Comment by pylessard** [comment]
How is your ram usage when that happens?
Possibly the internal queue that is full

**Comment by sylar89ash** [comment]
No, as it is quite randomly observed, I have not taken any note of RAM usage, will check it now.
And the internal queue must not be full as I have faced this issue just after booting the system and running the code for first time.

**Comment by pylessard** [comment]
Any update on this?

**Comment by sylar89ash** [comment]
Ya, so I checked the RAM usage as 23% and the queue is supposed to be empty as this happened in the first run itself.

**Comment by pylessard** [comment]
How do you ensure that the faulty step is `stack.process()`
How did you define your rxfn and txfn?

I need some input from you. stack.process is non-blocking.

**Comment by pylessard** [comment]
I am closing this issue as there is too few details to conclude that there really is an issue to be investigated.
