### ISSUE TITLE
Python-can-isotp consume a asc file

### ISSUE THREAD

**Issue by Kheffache** [pylessard/python-can-isotp#54]
Hi, i want to know if the Python-can-isotp can consume a CAN log file (.asc .txt ...) to extract the payload of the frame that are CAN TP data frames. If not any help on a possible solution ?

**Comment by hartkopp** [comment]
You can simply use the isotpsniffer from the can-utils https://github.com/linux-can/can-utils package.
Convert the asc to a log file (with asc2log) then replay the logfile to a virtual can (e.g. canplayer -I logfile.log vcan0=can0) and then run isotpsniffer on that vcan0 with the needed CAN-IDs to let the Linux kernel re-assemble the ISO-TP PDUs and print them.

**Comment by Kheffache** [comment]
> You can simply use the isotpsniffer from the can-utils https://github.com/linux-can/can-utils package. Convert the asc to a log file (with asc2log) then replay the logfile to a virtual can (e.g. canplayer -I logfile.log vcan0=can0) and then run isotpsniffer on that vcan0 with the needed CAN-IDs to let the Linux kernel re-assemble the ISO-TP PDUs and print them.

Thanks for your answer, but can this tool work under windows ?

**Comment by hartkopp** [comment]
Ehm - no. It uses the isotp implementation inside the Linux kernel. Sorry - was not part of the question ;-)

**Comment by pylessard** [comment]
Can we close this issue?
