### ISSUE TITLE
Add type hints

### ISSUE THREAD

**Issue by brent-stone** [pylessard/python-can-isotp#58]
### Issue
Type hints are needed for downstream projects to use mypy and other automated tooling

### Solution
Merge my pull request which includes a decent set of mypy stubs for the package.

### Alternatives
Add type hints throughout the package

### Context
These stubs satisfied mypy when I installed them into a local /stubs directory for a project that relies on can-isotp.

**Comment by pylessard** [comment]
#57 merged. Closing this issue.
