### ISSUE TITLE
Possibility to switch off Flow Control sending on Rx

### ISSUE THREAD

**Issue by toooooobi** [pylessard/python-can-isotp#59]
I have some projects where it is not necessary to send a flow control after reception of first frame
In my case another ECU is taking care of that.

Proposal: Implement a parameter to switch off flow control on reception, e.g.
![image](https://user-images.githubusercontent.com/41482498/151988142-3fb4b562-cf70-40e2-a0bf-4d59c7eebc25.png)

**Comment by toooooobi** [comment]
Hi Pierre,

actually the idea was to be able to transmit still, but having the option to turn off sending FC frames.

Is this also possible with the socket configuration?

Thank you.

**Comment by pylessard** [comment]
Fixed with Pull Request  #65
