### ISSUE TITLE
Comma is missing in IsoTp sockets example

### ISSUE THREAD

**Issue by vitkorob** [pylessard/python-can-isotp#97]
Comma is missing in IsoTp sockets example https://github.com/pylessard/python-can-isotp/blob/5345d1c07143dd6dd9e856c23e105c2db3f752bc/doc/source/isotp/socket.rst?plain=1#L68

**Comment by pylessard** [comment]
Thanks, will fix

**Comment by pylessard** [comment]
Fixed
