### ISSUE TITLE
How do I fill in padding byte in Flow Control messages?

### ISSUE THREAD

**Issue by dhje0ng** [pylessard/python-can-isotp#98]
```
flowcontrol.write() got an unexpected keyword argument 'txpad'
```

It says that the txpad param is not available.

The CAN devices I test always use a DLC length of 8 bytes with the
CAN messages with a DLC length of 8 bytes, so the Flow control must also contain a padding byte where XX is 30 00 05 XX XX XX XX XX XX to get a positive response.

Otherwise, it will send a flow control message and not response.

How can you help me?

**Comment by pylessard** [comment]
I understand that you are configuring a socket.
txpad is a general option and should apply to all messages that goes out of that socket.
Is that an issue?

**Comment by dhje0ng** [comment]
아닙니다. 이것은 제 착오였으며, 

```
s = isotp.socket(3)
s.set_opts(txpad=8)
s.set_fc_opts(stmin=5, bs=30)
```

다음과 같이 해결 할 수 있습니다. 답변을 주셔서 감사합니다
문제를 닫겠습니다.
